import type { ChapitrePedagogique, DomainePedagogique } from '@/types/content'

export const domaines: DomainePedagogique[] = [
  {
    id: 'fondements',
    slug: 'fondements',
    titre: 'Fondements',
    resume: "Comprendre ce qu'est vraiment une idée créative et les capacités qui la rendent viable.",
    intention: "Installer une définition exigeante de la créativité avant de parler de méthodes.",
    couleur: 'from-emerald-500/30 via-teal-500/15 to-transparent',
    icone: 'Compass',
  },
  {
    id: 'philosophie',
    slug: 'philosophie-de-travail',
    titre: 'Philosophie de travail créatif',
    resume: 'Apprendre à alterner production, tri, maturation et concrétisation sans se bloquer trop tôt.',
    intention: "Poser le bon état d'esprit de travail, loin du mythe de l'inspiration instantanée.",
    couleur: 'from-amber-500/30 via-orange-500/15 to-transparent',
    icone: 'Flame',
  },
  {
    id: 'modes-pensee',
    slug: 'modes-de-pensee',
    titre: 'Modes de pensée',
    resume: 'Mobiliser plusieurs logiques pour ouvrir, décentrer, densifier et stabiliser une piste.',
    intention: 'Sortir de la pensée unique en combinant divergence, tri, analogies et systémique.',
    couleur: 'from-sky-500/30 via-cyan-500/15 to-transparent',
    icone: 'Network',
  },
  {
    id: 'leviers',
    slug: 'leviers-fondamentaux',
    titre: 'Leviers fondamentaux',
    resume: 'Transformer une base existante en idée forte par association, déformation, tension et signature.',
    intention: 'Donner des gestes de création concrets pour enrichir une piste existante.',
    couleur: 'from-rose-500/30 via-orange-500/15 to-transparent',
    icone: 'Wand2',
  },
  {
    id: 'methodes',
    slug: 'methodes-de-generation',
    titre: "Méthodes de génération",
    resume: 'Utiliser des moteurs ciblés pour produire des pistes quand le champ paraît trop fermé.',
    intention: "Transformer les concepts en protocoles de génération immédiatement utilisables.",
    couleur: 'from-lime-500/30 via-emerald-500/15 to-transparent',
    icone: 'Sparkles',
  },
  {
    id: 'imagination',
    slug: 'imagination',
    titre: 'Imagination',
    resume: "Nourrir la matière mentale, visualiser, simuler et laisser mûrir pour enrichir l'inventivité.",
    intention: 'Rendre le travail imaginaire plus incarné et plus riche que la simple image mentale.',
    couleur: 'from-indigo-500/30 via-sky-500/15 to-transparent',
    icone: 'Eye',
  },
  {
    id: 'transformation',
    slug: 'freins-et-transformation',
    titre: 'Freins et transformation',
    resume: "Repérer les blocages, externaliser tôt, évaluer avec nuance et retravailler jusqu'à une forme forte.",
    intention: 'Passer du blocage à une amélioration méthodique des idées.',
    couleur: 'from-red-500/30 via-rose-500/15 to-transparent',
    icone: 'ShieldAlert',
  },
  {
    id: 'pratique',
    slug: 'protocoles-et-pratique',
    titre: 'Protocoles et pratique',
    resume: 'Structurer les séances, diagnostiquer, évaluer et installer une progression dans la durée.',
    intention: 'Transformer la fiche maîtresse en véritable système de travail quotidien.',
    couleur: 'from-stone-500/30 via-slate-500/15 to-transparent',
    icone: 'NotebookText',
  },
]

export const chapitres: ChapitrePedagogique[] = [
  {
    id: 'ce-quest-creativite',
    slug: 'ce-quest-creativite',
    domaineId: 'fondements',
    titre: "Ce qu'est vraiment la créativité",
    resume: 'Définition solide, critères de valeur et capacités qui composent le travail créatif.',
    objectif: "Éviter la confusion entre étrangeté, nouveauté, imagination et valeur réelle.",
    conceptIds: ['definition-creativite', 'piliers-creativite'],
  },
  {
    id: 'principes-fondamentaux',
    slug: 'principes-fondamentaux',
    domaineId: 'philosophie',
    titre: 'Principes fondamentaux',
    resume: 'Huit principes pour organiser le travail créatif sans casser trop tôt une piste prometteuse.',
    objectif: "Construire une discipline de travail plus fiable que l'attente d'une idée parfaite.",
    conceptIds: ['principes-travail-creatif'],
  },
  {
    id: 'ouvrir-et-trier',
    slug: 'ouvrir-et-trier',
    domaineId: 'modes-pensee',
    titre: 'Ouvrir puis trier',
    resume: 'Produire un large champ de pistes puis le resserrer sans brutalité.',
    objectif: 'Savoir alterner divergence et convergence au bon moment.',
    conceptIds: ['pensee-divergente', 'pensee-convergente'],
  },
  {
    id: 'decentrer-et-donner-sens',
    slug: 'decentrer-et-donner-sens',
    domaineId: 'modes-pensee',
    titre: 'Décentrer et donner du sens',
    resume: 'Penser par analogie, inversion, symboles et systèmes pour sortir des réflexes habituels.',
    objectif: 'Explorer des angles qui déplacent la structure du problème, pas seulement sa surface.',
    conceptIds: [
      'pensee-analogique',
      'pensee-inversee',
      'pensee-symbolique',
      'pensee-systemique',
    ],
  },
  {
    id: 'transformer-la-base',
    slug: 'transformer-la-base',
    domaineId: 'leviers',
    titre: 'Transformer la base',
    resume: "Associer, déformer et changer d'angle pour faire émerger autre chose qu'une simple copie.",
    objectif: 'Créer de nouvelles structures à partir du connu.',
    conceptIds: ['associer-idees-eloignees', 'deformer-existant', 'changer-point-de-vue'],
  },
  {
    id: 'densifier-la-piste',
    slug: 'densifier-la-piste',
    domaineId: 'leviers',
    titre: 'Densifier la piste',
    resume: "Ajouter des couches, de la tension, retirer le banal et affirmer une identité propre.",
    objectif: 'Passer d’une idée plate à une idée dense, lisible et mémorable.',
    conceptIds: [
      'superposer-couches',
      'rendre-concret',
      'chercher-tension',
      'eliminer-banal',
      'signature-unique',
    ],
  },
  {
    id: 'moteurs-de-generation',
    slug: 'moteurs-de-generation',
    domaineId: 'methodes',
    titre: 'Moteurs de génération',
    resume: 'Méthodes courtes pour déclencher rapidement des pistes neuves et utilisables.',
    objectif: "Avoir des outils précis quand l'exploration stagne ou tourne en rond.",
    conceptIds: [
      'combinaison-forcee',
      'matrice-creative',
      'contrainte-volontaire',
      'reformuler-vrai-probleme',
    ],
  },
  {
    id: 'matiere-mentale',
    slug: 'matiere-mentale',
    domaineId: 'imagination',
    titre: 'Matière mentale',
    resume: "Nourrir l'esprit, visualiser, simuler et varier pour enrichir l'imaginaire.",
    objectif: "Développer une imagination plus incarnée, plus souple et moins pauvre en matériaux.",
    conceptIds: [
      'nourrir-son-esprit',
      'visualisation-mentale',
      'simulation-mentale',
      'variation-systematique',
      'journal-creatif',
      'incubation',
    ],
  },
  {
    id: 'freins-courants',
    slug: 'freins-courants',
    domaineId: 'transformation',
    titre: 'Freins courants',
    resume: 'Repérer les blocages qui empêchent une idée de naître, de se clarifier ou de se renforcer.',
    objectif: 'Diagnostiquer vite ce qui bloque une séance créative.',
    conceptIds: ['freins-creatifs'],
  },
  {
    id: 'solidifier-une-idee',
    slug: 'solidifier-une-idee',
    domaineId: 'transformation',
    titre: 'Solidifier une idée',
    resume: 'Écrire tôt, évaluer, itérer puis simplifier pour transformer une piste brute en forme forte.',
    objectif: 'Faire passer une piste brute à une forme forte sans perdre sa singularité.',
    conceptIds: ['externaliser-tot', 'evaluer-idee', 'iterer-une-idee', 'simplifier-sans-appauvrir'],
  },
  {
    id: 'protocole',
    slug: 'protocole',
    domaineId: 'pratique',
    titre: 'Protocole et diagnostics',
    resume: 'Cadre complet de séance, diagnostic de blocage et évaluation finale.',
    objectif: 'Avoir une méthode de séance reproductible et des repères de décision.',
    conceptIds: ['protocole-seance-creative', 'grille-diagnostic', 'grille-evaluation'],
  },
  {
    id: 'usage-long-terme',
    slug: 'usage-long-terme',
    domaineId: 'pratique',
    titre: 'Usage long terme',
    resume: "Checklist courte, maximes et mode d'emploi pour inscrire l'entraînement dans la durée.",
    objectif: 'Transformer une bonne séance isolée en système de progression.',
    conceptIds: ['checklist-ultra-courte', 'maximes-utiles', 'mode-emploi'],
  },
]
