import type { ExerciceCreatif } from '@/types/content'

export const exercices: ExerciceCreatif[] = [
  {
    id: 'production-massive',
    slug: 'production-massive',
    titre: 'Production massive',
    competence: 'divergence',
    dureeMinutes: 12,
    difficulte: 'base',
    objectif: 'Dépasser les évidences et créer du volume avant tout tri.',
    consignes: [
      'Choisis un sujet précis.',
      'Liste 10 idées faciles, 10 idées étranges, 10 idées absurdes et 10 idées potentiellement fortes.',
      'Ne barre rien pendant la production.',
    ],
    variantes: ['Réduis à 5 minutes pour un échauffement rapide.', 'Fais une seconde manche depuis un point de vue opposé.'],
    promptDeNote: 'Quelles idées ont commencé faibles mais semblent plus fertiles après relecture ?',
    notionIds: ['pensee-divergente', 'principes-travail-creatif'],
    tags: ['divergence', 'volume', 'echauffement'],
  },
  {
    id: 'analogies-croisees',
    slug: 'analogies-croisees',
    titre: 'Analogies croisées',
    competence: 'analogie',
    dureeMinutes: 10,
    difficulte: 'intermediaire',
    objectif: 'Importer des structures depuis des domaines éloignés.',
    consignes: [
      'Décris ton sujet comme une ruche, une tempête, un rituel et une ville.',
      'Pour chaque analogie, liste trois règles ou tensions transférables.',
      'Garde la logique utile, pas seulement l’image.',
    ],
    promptDeNote: "Quelle analogie a déplacé le problème de la manière la plus fertile ?",
    notionIds: ['pensee-analogique', 'changer-point-de-vue'],
    tags: ['analogie', 'transfert', 'decentrement'],
  },
  {
    id: 'deformations-5',
    slug: 'deformations-5',
    titre: 'Les 5 transformations',
    competence: 'deformation',
    dureeMinutes: 9,
    difficulte: 'base',
    objectif: 'Voir comment une même idée change quand on tord sa logique.',
    consignes: [
      'Prends une idée de départ.',
      'Inverse-la, agrandis-la, réduis-la, rends-la vivante et rends-la symbolique.',
      'Compare ensuite les versions obtenues.',
    ],
    promptDeNote: 'Quelle transformation a révélé quelque chose de vraiment neuf ?',
    notionIds: ['deformer-existant', 'pensee-inversee', 'pensee-symbolique'],
    tags: ['deformation', 'variation', 'structure'],
  },
  {
    id: 'reformulations-probleme',
    slug: 'reformulations-probleme',
    titre: '10 reformulations',
    competence: 'reformulation',
    dureeMinutes: 8,
    difficulte: 'base',
    objectif: 'Éviter de résoudre la mauvaise question.',
    consignes: [
      'Écris 10 formulations différentes du même problème.',
      'Varie le niveau : concret, humain, systémique, émotionnel, temporel.',
      'Choisis celle qui ouvre le plus de pistes crédibles.',
    ],
    promptDeNote: 'Quelle reformulation change le plus la qualité des solutions possibles ?',
    notionIds: ['reformuler-vrai-probleme', 'protocole-seance-creative'],
    tags: ['probleme', 'cadrage', 'clarte'],
  },
  {
    id: 'elimination-banal',
    slug: 'elimination-banal',
    titre: 'Élimination du banal',
    competence: 'filtrage',
    dureeMinutes: 7,
    difficulte: 'base',
    objectif: 'Retirer le cliché principal pour faire apparaître une identité plus forte.',
    consignes: [
      'Choisis une idée ou une solution que tu trouves trop générique.',
      'Supprime son cliché principal.',
      'Propose trois remplacements plus spécifiques, plus vivants ou plus justes.',
    ],
    promptDeNote: 'Quel élément supprimé rendait vraiment l’idée interchangeable ?',
    notionIds: ['eliminer-banal', 'signature-unique'],
    tags: ['banal', 'signature', 'filtrage'],
  },
  {
    id: 'signature-en-phrase',
    slug: 'signature-en-phrase',
    titre: 'Phrase de signature',
    competence: 'signature',
    dureeMinutes: 6,
    difficulte: 'base',
    objectif: 'Nommer le noyau singulier d’une idée.',
    consignes: [
      'Prends une idée que tu veux clarifier.',
      "Résume-la en une phrase qui commence par : 'Ce n'est pas seulement..., c'est...'.",
      'Réécris la phrase jusqu’à ce que sa singularité soit nette.',
    ],
    promptDeNote: 'Quel détail ou quelle règle donne réellement sa saveur à cette idée ?',
    notionIds: ['signature-unique', 'simplifier-sans-appauvrir'],
    tags: ['signature', 'synthese', 'identite'],
  },
  {
    id: 'combinaison-forcee',
    slug: 'atelier-combinaison-forcee',
    titre: 'Combinaison forcée',
    competence: 'combinaison',
    dureeMinutes: 8,
    difficulte: 'intermediaire',
    objectif: 'Forcer une structure nouvelle entre des éléments éloignés.',
    consignes: [
      'Choisis quatre mots sans rapport.',
      'Interdis-toi d’en retirer un.',
      'Invente le système qui les relie réellement.',
    ],
    promptDeNote: 'Quelle règle rend la fusion crédible au lieu de simplement étrange ?',
    notionIds: ['combinaison-forcee', 'associer-idees-eloignees'],
    tags: ['combinaison', 'friction', 'generation'],
  },
  {
    id: 'tension-centrale',
    slug: 'tension-centrale',
    titre: 'Tension centrale',
    competence: 'tension',
    dureeMinutes: 7,
    difficulte: 'intermediaire',
    objectif: 'Donner du relief à une idée en formulant son conflit ou son prix.',
    consignes: [
      'Choisis une idée prometteuse.',
      'Écris ce qu’elle apporte, ce qu’elle retire et le prix à payer.',
      'Résume la tension centrale en une phrase.',
    ],
    promptDeNote: 'Cette tension rend-elle la piste plus intéressante ou seulement plus compliquée ?',
    notionIds: ['chercher-tension', 'evaluer-idee'],
    tags: ['tension', 'relief', 'decision'],
  },
  {
    id: 'simulation-usage',
    slug: 'simulation-usage',
    titre: "Simulation d'usage",
    competence: 'simulation',
    dureeMinutes: 9,
    difficulte: 'intermediaire',
    objectif: 'Tester la réalité intérieure d’une piste avant prototype.',
    consignes: [
      'Choisis une scène d’usage précise.',
      'Simule 5 minutes minute par minute.',
      'Repère les moments d’ennui, de friction et de surprise.',
    ],
    promptDeNote: 'À quel moment la piste devient-elle réellement vivante ?',
    notionIds: ['simulation-mentale', 'pensee-systemique', 'rendre-concret'],
    tags: ['simulation', 'usage', 'test'],
  },
  {
    id: 'visualisation-sensorielle',
    slug: 'visualisation-sensorielle',
    titre: 'Visualisation sensorielle',
    competence: 'visualisation',
    dureeMinutes: 6,
    difficulte: 'base',
    objectif: 'Rendre une scène plus incarnée grâce aux détails sensoriels.',
    consignes: [
      'Imagine une scène liée à ton idée.',
      'Décris-la avec la vue, le son, la texture, la température et le rythme.',
      'Ajoute ensuite ce qui surprend ou inquiète dans cette scène.',
    ],
    promptDeNote: 'Quel détail sensoriel a le plus densifié la scène ?',
    notionIds: ['visualisation-mentale', 'superposer-couches'],
    tags: ['sensoriel', 'incarnation', 'scene'],
  },
  {
    id: 'mauvaises-idees',
    slug: 'mauvaises-idees-volontaires',
    titre: 'Mauvaises idées volontaires',
    competence: 'desinhibition',
    dureeMinutes: 8,
    difficulte: 'base',
    objectif: 'Casser l’autocensure en produisant exprès des idées ratées.',
    consignes: [
      'Crée 10 idées volontairement horribles ou ridicules.',
      'Repère ensuite les fragments potentiellement sauvables.',
      'Sauve une seule piste et reformule-la sérieusement.',
    ],
    promptDeNote: 'Quel fragment sauvé était caché dans une mauvaise idée ?',
    notionIds: ['principes-travail-creatif', 'pensee-divergente', 'freins-creatifs'],
    tags: ['desinhibition', 'jugement', 'divergence'],
  },
  {
    id: 'point-de-vue-croise',
    slug: 'point-de-vue-croise',
    titre: 'Changement de point de vue',
    competence: 'perspective',
    dureeMinutes: 7,
    difficulte: 'base',
    objectif: 'Faire émerger des enjeux invisibles depuis ton angle habituel.',
    consignes: [
      'Prends une situation.',
      'Décris-la depuis cinq points de vue contrastés.',
      'Liste ensuite ce que chaque regard révèle comme opportunité ou problème.',
    ],
    promptDeNote: 'Quel regard a le plus déplacé ta compréhension du sujet ?',
    notionIds: ['changer-point-de-vue', 'pensee-systemique'],
    tags: ['perspective', 'empathie', 'decentrement'],
  },
  {
    id: 'concretisation-express',
    slug: 'concretisation-express',
    titre: 'Concrétisation express',
    competence: 'concretisation',
    dureeMinutes: 8,
    difficulte: 'base',
    objectif: 'Sortir rapidement de l’abstraction.',
    consignes: [
      'Choisis une idée floue.',
      'Décris sa fonction, sa forme, son usage, sa limite et son prototype minimal.',
      'Résume enfin la piste en une phrase simple.',
    ],
    promptDeNote: 'Quelle partie était la plus floue avant la concrétisation ?',
    notionIds: ['rendre-concret', 'externaliser-tot'],
    tags: ['prototype', 'clarte', 'concret'],
  },
  {
    id: 'routine-5-min',
    slug: 'routine-5-min',
    titre: 'Exercice rapide 5 min',
    competence: 'echauffement',
    dureeMinutes: 5,
    difficulte: 'base',
    objectif: 'Relancer une séance courte avec une contrainte simple et utile.',
    consignes: [
      'Choisis un sujet.',
      'Trouve 5 variantes, 3 tensions et 1 phrase de signature.',
      'Garde ensuite la piste qui reste la plus vivante.',
    ],
    promptDeNote: 'Quelle variation a le plus renforcé la piste en très peu de temps ?',
    notionIds: ['variation-systematique', 'chercher-tension', 'signature-unique'],
    tags: ['rapide', '5min', 'echauffement'],
  },
]
