import type { RoutineCreatif } from '@/types/content'

export const routines: RoutineCreatif[] = [
  {
    id: 'quotidienne-courte',
    slug: 'quotidienne-courte',
    titre: 'Routine quotidienne courte',
    resume: 'Un passage bref mais structuré pour garder le muscle créatif actif chaque jour.',
    objectif: 'Entretenir la divergence, la capture et la signature en moins de 15 minutes.',
    duree: '12 min',
    frequence: 'Tous les jours',
    progression: 'Échauffement > variation > capture',
    exercicesIds: ['routine-5-min', 'signature-en-phrase', 'visualisation-sensorielle'],
    notionIds: ['pensee-divergente', 'signature-unique', 'journal-creatif'],
    etapes: [
      '2 min : définir le sujet du jour.',
      '5 min : produire vite avec une contrainte légère.',
      '3 min : isoler une piste et lui donner une signature.',
      '2 min : noter ce qui mérite d’être repris plus tard.',
    ],
  },
  {
    id: 'hebdomadaire-structuree',
    slug: 'hebdomadaire-structuree',
    titre: 'Routine hebdomadaire structurée',
    resume: 'Une séance complète pour ouvrir, enrichir et choisir une piste sérieuse.',
    objectif: 'Passer une idée ou un problème par un mini protocole complet chaque semaine.',
    duree: '45 min',
    frequence: '1 fois par semaine',
    progression: 'Reformulation > divergence > enrichissement > tri',
    exercicesIds: ['reformulations-probleme', 'production-massive', 'tension-centrale', 'concretisation-express'],
    notionIds: ['protocole-seance-creative', 'reformuler-vrai-probleme', 'evaluer-idee'],
    etapes: [
      '10 min : reformuler le vrai problème.',
      '15 min : divergence ou combinaison forcée.',
      '10 min : tension + signature + concretisation.',
      '10 min : évaluation et décision sur la suite.',
    ],
  },
  {
    id: 'approfondie',
    slug: 'approfondie',
    titre: 'Routine approfondie',
    resume: 'Une séance longue pour transformer une idée brute en concept solide et testable.',
    objectif: 'Travailler une seule piste jusqu’à la rendre dense, claire et incarnable.',
    duree: '90 min',
    frequence: '1 à 2 fois par mois',
    progression: 'Exploration > enrichissement > simulation > itération',
    exercicesIds: ['analogies-croisees', 'deformations-5', 'simulation-usage', 'concretisation-express'],
    notionIds: ['pensee-analogique', 'deformer-existant', 'simulation-mentale', 'iterer-une-idee'],
    etapes: [
      '15 min : clarifier le sujet et reformuler.',
      '25 min : générer avec analogies, inversions et combinaisons.',
      '20 min : enrichir avec couches, tension et signature.',
      '15 min : simuler l’usage.',
      '15 min : itérer puis simplifier.',
    ],
  },
  {
    id: 'personnalisable',
    slug: 'personnalisable',
    titre: 'Routine personnalisable simple',
    resume: 'Un cadre souple pour composer une routine à partir de ton pilier faible du moment.',
    objectif: 'Adapter la pratique à ton besoin actuel : divergence, tri, concretisation ou variation.',
    duree: '10 à 30 min',
    frequence: 'Libre',
    progression: 'Diagnostic > choix du levier > pratique ciblée',
    exercicesIds: ['production-massive', 'point-de-vue-croise', 'concretisation-express', 'simulation-usage'],
    notionIds: ['piliers-creativite', 'grille-diagnostic', 'mode-emploi'],
    etapes: [
      'Choisis un pilier faible ou un blocage principal.',
      'Sélectionne un exercice court aligné.',
      'Ajoute une note de retour pour ajuster la prochaine séance.',
    ],
  },
]
