import type { BlocReference, EtapeAtelier } from '@/types/content'

export const etapesAtelier: EtapeAtelier[] = [
  {
    id: 'idee-depart',
    slug: 'idee-depart',
    titre: 'Idée de départ',
    intention: 'Clarifier la matière brute avec laquelle tu commences.',
    description: "Poser le point de départ sans chercher à être déjà brillant ou finalisé.",
    questions: [
      "Quelle est l'idée, le projet ou la situation de départ ?",
      "Qu'est-ce qui t'attire ou t'agace dans ce sujet ?",
      "Qu'est-ce qui reste encore flou ?",
    ],
    sousPrompts: ['Décris la situation actuelle.', 'Nommes-en le noyau en une phrase.', 'Note ce qui te semble prometteur.'],
    notionIds: ['definition-creativite', 'externaliser-tot'],
    livrable: 'Une formulation simple du point de départ et de son intérêt.',
  },
  {
    id: 'vrai-probleme',
    slug: 'vrai-probleme',
    titre: 'Reformuler le vrai problème',
    intention: 'Changer le cadrage pour ouvrir un meilleur espace de solution.',
    description: 'Passer de la demande apparente à la question réellement fertile.',
    questions: [
      'Quel est le vrai problème derrière le problème ?',
      'Quelle version du sujet ouvre le plus de solutions pertinentes ?',
      'Quelle formulation est trop étroite ou trompeuse ?',
    ],
    sousPrompts: ['Écris plusieurs formulations.', 'Varie les niveaux de lecture.', 'Choisis la reformulation la plus féconde.'],
    notionIds: ['reformuler-vrai-probleme', 'pensee-inversee'],
    livrable: 'Une reformulation claire et féconde du sujet.',
  },
  {
    id: 'divergence',
    slug: 'divergence',
    titre: 'Ouvrir le champ',
    intention: 'Produire de la matière avant toute décision.',
    description: 'Ouvrir largement les pistes possibles pour ne pas rester prisonnier des évidences.',
    questions: [
      'Quelles sont les premières idées évidentes ?',
      'Quelles autres directions apparaissent après fatigue ?',
      'Quelle piste paraît étrange mais exploitable ?',
    ],
    sousPrompts: ['Trouve 20 à 30 pistes.', 'Varie les angles.', 'Ne trie pas encore.'],
    notionIds: ['pensee-divergente', 'combinaison-forcee', 'contrainte-volontaire'],
    livrable: 'Une liste large de pistes ou directions.',
  },
  {
    id: 'analogies',
    slug: 'analogies',
    titre: 'Analogies',
    intention: 'Déplacer la structure du problème grâce à des domaines extérieurs.',
    description: 'Importer des logiques qui n’apparaissent pas depuis le cadre habituel.',
    questions: [
      'Si ce sujet était une ville, une ruche ou un jardin, que changerait cette lecture ?',
      'Quelle logique étrangère pourrais-tu importer ?',
      'Quel domaine révèle la meilleure structure cachée ?',
    ],
    sousPrompts: ['Teste trois analogies fortes.', 'Extrait des règles, pas seulement des images.', 'Garde la plus fertile.'],
    notionIds: ['pensee-analogique', 'nourrir-son-esprit'],
    livrable: 'Une ou deux analogies structurantes avec leurs enseignements.',
  },
  {
    id: 'deformations',
    slug: 'deformations',
    titre: 'Déformations et inversions',
    intention: 'Tordre la piste pour voir ce qu’elle peut devenir.',
    description: 'Appliquer des transformations qui changent la logique plutôt que la surface.',
    questions: [
      'Que devient l’idée si tu l’inverses ?',
      'Que se passe-t-il si tu changes son échelle ou sa fonction ?',
      'Quelle déformation révèle un potentiel inattendu ?',
    ],
    sousPrompts: ['Inverse.', 'Exagère.', 'Réduis.', 'Déplace.', 'Rends vivant.'],
    notionIds: ['deformer-existant', 'pensee-inversee', 'variation-systematique'],
    livrable: 'Trois variantes fortes issues des transformations.',
  },
  {
    id: 'couches-signature',
    slug: 'couches-signature',
    titre: 'Couches, tension et signature',
    intention: 'Donner de la densité, du relief et une identité propre à la piste.',
    description: 'Enrichir la piste avec du sens, une tension et un trait distinctif.',
    questions: [
      'Quelle tension centrale porte cette idée ?',
      'Quelles couches émotionnelles, symboliques ou sociales lui manquent ?',
      'Quel détail peut devenir sa signature ?',
    ],
    sousPrompts: ['Ajoute une couche.', 'Formule une tension.', 'Écris une phrase de signature.'],
    notionIds: ['superposer-couches', 'chercher-tension', 'signature-unique'],
    livrable: 'Une version densifiée avec tension et signature claire.',
  },
  {
    id: 'concretisation',
    slug: 'concretisation',
    titre: 'Rendre concret',
    intention: 'Transformer la piste enrichie en chose claire et montrable.',
    description: 'Définir comment la piste fonctionne, pour qui et sous quelle forme minimale.',
    questions: [
      "Qu'est-ce que c'est exactement ?",
      'Qui l’utilise et dans quelle scène ?',
      'Quel est le prototype minimal ?',
    ],
    sousPrompts: ['Décris la forme.', 'Décris l’usage.', 'Décris les limites.'],
    notionIds: ['rendre-concret', 'simulation-mentale'],
    livrable: 'Une version concrète, testable et explicable.',
  },
  {
    id: 'evaluation',
    slug: 'evaluation',
    titre: 'Évaluer',
    intention: 'Prendre du recul sans casser ce qui mérite encore une itération.',
    description: 'Mesurer la clarté, la singularité, la cohérence, la fertilité et la faisabilité.',
    questions: [
      'Est-ce fort, clair et mémorable ?',
      'Que faut-il encore retravailler ?',
      'Cette piste mérite-t-elle du temps supplémentaire ?',
    ],
    sousPrompts: ['Passe la grille.', 'Repère les déséquilibres.', 'Décide de la suite.'],
    notionIds: ['evaluer-idee', 'grille-evaluation'],
    livrable: 'Une décision argumentée : poursuivre, retravailler ou mettre en pause.',
  },
  {
    id: 'synthese',
    slug: 'synthese',
    titre: 'Synthèse',
    intention: 'Formuler le noyau final de la piste et les prochaines étapes.',
    description: 'Résumer ce qui tient, ce qui reste fragile et ce qui doit suivre.',
    questions: [
      'Quel est le noyau de l’idée ?',
      'Quels sont ses points forts ?',
      'Quels points restent à retravailler ?',
      'Quelle prochaine piste concrète veux-tu suivre ?',
    ],
    sousPrompts: ['Écris une phrase noyau.', 'Liste les forces.', 'Liste les points à revoir.', 'Fixe la prochaine action.'],
    notionIds: ['simplifier-sans-appauvrir', 'mode-emploi'],
    livrable: 'Une synthèse claire avec prochaines actions.',
  },
]

export const blocsReference: BlocReference[] = [
  {
    id: 'grille-diagnostic-rapide',
    titre: 'Diagnostic rapide',
    description: "À relire quand une séance bloque ou s'épuise.",
    items: [
      'Ai-je mal défini le problème ?',
      'Ai-je produit trop peu ?',
      'Ai-je jugé trop tôt ?',
      'Ai-je oublié la tension ?',
      'Ai-je trop peu externalisé ?',
      'Ai-je besoin d’incubation ?',
    ],
  },
  {
    id: 'checklist-courte',
    titre: 'Checklist ultra courte',
    description: 'Le rappel de poche issu de la fiche maîtresse.',
    items: [
      'Quel est le vrai problème ?',
      'Ai-je assez ouvert le champ ?',
      'Ai-je utilisé plusieurs moteurs de pensée ?',
      'Ai-je retiré le banal ?',
      'Ai-je rendu concret, simulé et itéré ?',
      'Ai-je simplifié sans tuer l’idée ?',
    ],
  },
]
